### ISSUE TITLE
Facing an Issue while assessing M365

### ISSUE THREAD

**Issue by rc-ranjith** [jonrau1/ElectricEye#288]
**About the Issue**
I'm facing an issue with auditing my M365. I've added the Client ID, Client Secret, Tenant ID and Tenant Location in the `external_providers.toml` file as mentioned in the documentation.

![image](https://github.com/user-attachments/assets/7bc695aa-cd7e-4784-bbef-d4a68afc9b58)

Any help would be appreciated!!

**Comment by jonrau1** [comment]
Thanks for the report. I will have a fix for this soon. It's attempting to use STS to fill in an AWS Account ID but for these non-AWS checks I will hardcode an account ID instead.

**Comment by rc-ranjith** [comment]
Thanks for your quick reply, looking forward on the fix 🫡

**Comment by jonrau1** [comment]
@rc-ranjith pushed a change that doesn't use Boto3, since the default format for findings is ASFF/Security Hub I have to put *something* there.

It's in another branch, here's the commit if you want to try it yourself https://github.com/jonrau1/ElectricEye/commit/abb2c92831e75343ed2d48ef6c990e00a6a65c9b

Also if there are any other M365 checks you'd like me to include feel free to open another Issue. I'll keep this one opened until you confirm it's fixed for you

**Comment by rc-ranjith** [comment]
@jonrau1 Thanks for the update, I tried the latest commit. Still I'm getting these errors. 

<img width="599" alt="SSPM-Issue_2" src="https://github.com/user-attachments/assets/9e511cc1-83c8-4546-bc4d-812e87b30bb0">
