### ISSUE TITLE
How are compliance checks pre-populated in Auditors? 

### ISSUE THREAD

**Issue by abhinavbom** [jonrau1/ElectricEye#97]
For example, each auditor has compliance violations pre-populated for every violation. 
   "RelatedRequirements": [
                            "NIST CSF DE.AE-3",
                            "NIST SP 800-53 AU-6",
                            "NIST SP 800-53 CA-7",
                            "NIST SP 800-53 IR-4",
                            "NIST SP 800-53 IR-5",
                            "NIST SP 800-53 IR-8",
                            "NIST SP 800-53 SI-4",
                            "AICPA TSC CC7.2",
                            "ISO 27001:2013 A.12.4.1",
                            "ISO 27001:2013 A.16.1.7",
                        ]

How is this decided or mapped?

**Comment by jonrau1** [comment]
@abhinavbom I mapped them myself. Most of this was started when I was actually on the AWS Security Hub team before we made the decision to go with the Foundational Security Best Practices standard versus continuing to churn out framework-specific standards.

I did the primary mapping to NIST CSF and mapped to ISO, 800-53 from CSF and mapped backwards from SOC COSO/TSCs using AICPA's mapping into NIST 800-53. I cover some of that in depth in the FAQ.

**Comment by jonrau1** [comment]
Closing this. Feel free to re-open if you had more questions or wanted to submit a PR against the topic for updates.

**Comment by abhinavbom** [comment]
@jonrau1 Thanks for the clarification. Another point I am trying to understand is the coverage part. Not everything in these compliance standards can be covered through checks in the cloud env. Is that correct? How do we lay a common ground on what can be checked using a tool like ElectricEye Vs what cannot be? (Eg: do you have an IR program in place).

**Comment by jonrau1** [comment]
@abhinavbom I never actually went through and did reverse coverage on what wasn't mapped - it'd be situational - while there are a lot of similar mappings for thematically similar controls (e.g., encryption-at-rest checks are all mapped the same whether it is DynamoDB, EBS, Neptune, etc.) but there are a handful that are very specialized and just because you can satisfy a compliance requirement for a specific control for a specific service doesn't necessarily mean you'd be "covered" from a regulatory perspective.

Both NIST CSF & NIST 800-53 do not have formalized auditing organizations or standards behind it, AICPA TSCs are used by the AICPA sure - but every auditor has their own way they want evidence and samples controls in their own way, and ISO27001 is very stringent in ISMS definitions and what controls are checked.

So that is all to say that it wouldn't deliver much value to do so as not everyone will be using the same services in the same way - really the best way to assess this is to work with an actual auditor who can help identify gaps in Process / People related controls as ElectricEye is firmly Technical control oriented
